#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/udhcpc

#usb2eth drivers
insmod /root/usbnet.ko
insmod /root/dm9620.ko
insmod /root/asix.ko

PID=$(pidof -o %PPID /usr/sbin/udhcpd)
case "$1" in
  start)
    stat_busy "Starting udhcpc daemon" 
    [ -z "$PID" ] && /usr/sbin/udhcpc $UDHCPC_ARGS
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon udhcpc
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping udhcpc daemon"
		[[ ! -z $PID ]] && kill $PID &> /dev/null
		if [[ $? -gt 0 ]]; then
			stat_fail
		else
			rm_daemon udhcpc
			stat_done
		fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
